<?
$aMenuLinks = Array(
    Array(
        "Клиенты и проекты",
        "/kabinet/admin/",
        Array(),
        Array("ICON"=>"mdi-file-outline"),
        ""
    ),
    Array(
        "Исполнения",
        "/kabinet/admin/performances/",
        Array(),
        Array("ICON"=>"mdi-cart-outline"),
        ""
    ),
    Array(
        "Финансы",
        "/kabinet/admin/finance/",
        Array(),
        Array("ICON"=>"mdi-border-all"),
        ""
    ),
    Array(
        "Пользователи",
        "/kabinet/admin/users/",
        Array(),
        Array("ICON"=>"mdi-border-all"),
        ""
    ),
    Array(
        "Рассылка",
        "/kabinet/admin/malling/",
        Array(),
        Array("ICON"=>"mdi-border-all"),
        ""
    ),
    Array(
        "Все сообщения",
        "/kabinet/admin/notifications/",
        Array(),
        Array("ICON"=>"mdi-border-all"),
        ""
    ),
);
?>